#!/usr/bin/bash

#initial command for package developing
#env: DEVTOOLS_HOME
#

CMD_PATH=`dirname $0`

#
#export/system only work for its subprocesses.
#
#if [ "x$DEVTOOLS_HOME" == "x" ]; then 
#	echo "export DEVTOOLS_HOME=${CMD_PATH}"
#	export DEVTOOLS_HOME=${CMD_PATH}
#fi

perl ${CMD_PATH}/pkg.pl "$@"
