#!/usr/bin/bash

#initial command for package developing
#env: DEVTOOLS_HOME
#

CMD_PATH=`dirname $0`

if [ "x$DEVTOOLS_HOME" == "x" ]; then 
	echo "set DEVTOOLS_HOME to ${CMD_PATH}"
	export DEVTOOLS_HOME=${CMD_PATH}
fi

perl ${CMD_PATH}/pkg.pl "$@"
